Repository R3act-lion/YOURTRIP, pull requests merged in 2022-12, with the labels that each got.

#4 Feat : 공동 컴포넌트 구현 - 헤더, 내비게이션
  src/App.jsx
  src/assets/images/nav-profile-fill.svg
  src/assets/images/temp.txt
  src/components/Header/LogoHeader/LogoHeader.jsx
  src/components/Header/Navigation/Navigation.jsx
  src/components/Layout/LogoHeaderLayout/LogoHeaderLayout.jsx
  src/components/Layout/NavigationLayout/NavigationLayout.jsx
  src/components/temp.txt
  src/pages/Home/Home.jsx
  src/pages/Home/temp.txt
Labels: 📁 feat

#5 Feat : 이미지 모듈, 이미지 슬라이더 구현
  src/components/ImageSlide/ImageSlide.jsx
  src/modules/Image/Image.jsx
Labels: 📁 feat

#8 Feat : 버튼 모듈 제작
  src/modules/Button/Button.jsx
Labels: 📁 feat

#9 Feat : ThemeProvider 적용, theme 생성
  src/App.jsx
  src/theme.js
Labels: 📁 feat

#12 Fix : 라우터 연결 오류 수정
  src/components/LocationCategory/LocationCategory.jsx
  src/pages/Location/Location.jsx
Labels: 🚨 bug

#19 Feat : 공동 컴포넌트 구현 - 기본, 검색, 업로드 헤더 구현
  src/App.jsx
  src/components/Header/BasicHeader/BasicHeader.jsx
  src/components/Header/LogoHeader/LogoHeader.jsx
  src/components/Header/SearchHeader/SearchHeader.jsx
  src/components/Header/UploadHeader/UploadHeader.jsx
  src/components/Layout/BasicHeaderLayout/BasicHeaderLayout.jsx
  src/components/Layout/SearchHeaderLayout/SearchHeaderLayout.jsx
  src/components/Layout/UploadHeaderLayout/UploadHeaderLayout.jsx
Labels: 📁 feat

#16 Feat : 로그인및커뮤니티 공통 컴포넌트 구현
  src/assets/images/profile.svg
  src/components/CommuComentButton/CommuComentButton.jsx
  src/components/CommuHeartButton/CommuHeartButton.jsx
  src/components/CommuWritingButton/CommuWritingButton.jsx
  src/components/CommuprofileImg/CommuprofileImg.jsx
  src/components/LoginResultInput/ResultInput.jsx
  src/components/LoginTitle/HeaderTitle.jsx
  src/components/UploadImgButton/UploadImgButton.jsx
Labels: 📁 feat

#18 Feat : 지역 리스트 컴포넌트 구현
  src/App.jsx
  src/components/PlaceList/PlaceList.jsx
  깃허브 커밋 컨벤션.md
Labels: 📁 feat

#21 Feat : 공동 컴포넌트 구현 - 상품 리스트, 게시물 리스트, 테마 리스트
  src/App.jsx
  src/assets/images/test_duksu.png
  src/assets/images/test_gyeongbok.png
  src/assets/images/test_image1.png
  src/assets/images/test_image2.png
  src/components/Header/BasicHeader/BasicHeader.jsx
  src/components/Header/LogoHeader/LogoHeader.jsx
  src/components/Header/SearchHeader/SearchHeader.jsx
  src/components/Header/UploadHeader/UploadHeader.jsx
  src/components/Layout/NavigationLayout/NavigationLayout.jsx
  src/components/MainContainer/MainContainer.jsx
  src/components/Navigation/Navigation.jsx
  src/components/SlideList/DetailPlaceList/DetailImage.jsx
  src/components/SlideList/DetailPlaceList/DetailPlaceList.jsx
  src/components/SlideList/DetailPlaceList/DetailPlaceListItem.jsx
  src/components/SlideList/PostList/PostList.jsx
  src/components/SlideList/PostList/PostListItem.jsx
  src/components/SlideList/RecommendList/RecommendImage.jsx
  src/components/SlideList/RecommendList/RecommendList.jsx
  src/components/SlideList/RecommendList/RecommendListItem.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceList.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceListItem.jsx
  src/pages/Home/Home.jsx
Labels: 📁 feat

#26 Feat : 커뮤니티컴포넌트
  src/components/CommuDetailContent/CommuCotactImg.jsx
  src/components/CommuDetailContent/CommuDetailContent.jsx
  src/components/CommuHeartButton/CommuHeartButton.jsx
  src/components/CommuSeachContent/CommuSeachContent.jsx
  src/components/CommuSeachContent/CommuSeachImg.jsx
  src/components/CommuprofileImg/CommuprofileImg.jsx
  src/components/LoginTitle/HeaderTitle.jsx
  src/pages/Home/Home.jsx
Labels: 📁 feat

#30 Feat : 댓글 업로드 컴포넌트 구현
  src/App.jsx
  src/components/Comment/CommentUpload.jsx
Labels: 📁 feat

#34 Feat : 마이페이지 버튼 탭 클릭 시 해당 결과물 출력
  src/components/Profile/UserPlace/UserPlace.jsx
Labels: 📁 feat

#36 Feat : 회원가입 기능구현
  package-lock.json
  package.json
  src/App.jsx
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpProfile.jsx
  src/store/Register.js
Labels: 📁 feat

#42 Feat : 커뮤니티 피드 구현
  src/components/Post/PostItem/PostItem.jsx
  src/components/UserDesc/UserDesc.jsx
  src/pages/Community/CommunityUpload/CommunityUpload.jsx
Labels: 📁 feat

#44 Feat : Not Found 페이지 구현
  src/App.jsx
  src/assets/images/404Logo.svg
  src/components/SlideList/DetailPlaceList/DetailPlaceListItem.jsx
  src/pages/NotFound/NotFound.jsx
Labels: 📁 feat

#46 Feat : data fetch 및 화면 출력
  src/components/Layout/CategoryNavigationLayout/CategoryNavigationLayout.jsx
  src/components/LocationCategory/LocationCategory.jsx
  src/components/PlaceList/LocationList/LocationList.jsx
  src/components/PlaceList/NormalPlaceList/NormalPlaceList.jsx
  src/components/PlaceList/NormalPlaceList/NormalPlaceListItem.jsx
  src/components/Profile/UserPlace/UserPlace.jsx
  src/components/SlideList/DetailPlaceList/DetailPlaceList.jsx
  src/components/SlideList/DetailPlaceList/DetailPlaceListItem.jsx
  src/components/SlideList/RecommendList/RecommendList.jsx
  src/components/SlideList/RecommendList/RecommendListItem.jsx
  src/components/SlideList/RecommendPlaceList/RecommendPlaceList.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceList.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceListItem.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomePlaceList/HomePlaceList.jsx
  src/pages/Location/Location.jsx
  src/pages/Location/LocationPlaceList/LocationPlaceList.jsx
  src/pages/Location/LocationTheme/LocationTheme.jsx
  src/pages/PlaceDetail/PlaceDetail.jsx
Labels: 📁 feat

#48 Feat : 여행지 지도 구현
  public/index.html
  src/components/Comment/PlaceComment/PlaceCommentList.jsx
  src/index.jsx
  src/pages/PlaceDetail/PlaceDetail.jsx
Labels: 📁 feat

#51 Fix : 지역별 페이지 출력 에러 수정
  src/components/Layout/CategoryNavigationLayout/CategoryNavigationLayout.jsx
Labels: 🔧 Fix

#53 Feat : 로그인및회원가입에러메세지
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpProfile.jsx
Labels: 📁 feat

#55 Feat : 프로필 팔로잉 유저 리스트 페이지 구현
  src/assets/images/btn-follow.svg
  src/assets/images/btn-unfollow.svg
  src/components/FollowingBtn/FollowingBtn.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/ProfileFollowing/ProfileFollowing.jsx
Labels: 📁 feat

#56 Fix : 데이터 출력 수정
  src/App.jsx
  src/components/PlaceList/LocationList/LocationList.jsx
  src/components/PlaceList/NormalPlaceList/NormalPlaceList.jsx
  src/components/SlideList/DetailPlaceList/DetailPlaceList.jsx
  src/components/SlideList/DetailPlaceList/DetailPlaceListItem.jsx
  src/components/SlideList/RecommendList/RecommendList.jsx
  src/components/SlideList/RecommendList/RecommendListItem.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceList.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceListItem.jsx
  src/index.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomePlaceList/HomePlaceList.jsx
  src/pages/Location/Location.jsx
  src/pages/Location/LocationPlaceList/LocationPlaceList.jsx
  src/pages/Location/LocationTheme/LocationTheme.jsx
  src/pages/Location/temp.txt
  src/pages/PlaceDetail/PlaceDetail.jsx
  src/store/Data.js
  src/store/Register.js
Labels: 📁 feat

#58 Feat : 프로필 팔로워 유저 리스트 페이지 구현
  src/components/FollowingBtn/FollowingBtn.jsx
  src/components/UserDesc/UserDesc.jsx
  src/pages/Profile/ProfileFollowers/ProfileFollowers.jsx
  src/pages/Profile/ProfileFollowing/ProfileFollowing.jsx
Labels: 📁 feat

#60 Feat : 게시물 업로드 페이지 사진 미리보기 기능
  src/components/FollowingBtn/FollowingBtn.jsx
  src/pages/Community/CommunityUpload/CommunityUpload.jsx
Labels: 📁 feat

#63 Fix : 피드 정보 불러오기 기능 수정
  src/components/Header/BasicHeader/BasicHeader.jsx
  src/components/Header/LogoMoreHeader/LogoMoreHeader.jsx
  src/components/Layout/LogoMoreHeaderLayout/LogoMoreHeaderLayout.jsx
  src/components/Post/PostItem/PostItem.jsx
  src/components/Post/PostList/PostList.jsx
  src/components/UserDesc/UserDesc.jsx
  src/pages/Community/Community.jsx
  src/pages/Community/CommunityUpload/CommunityUpload.jsx
  src/pages/Profile/ProfileFollowing/ProfileFollowing.jsx
Labels: 🚨 bug

#67 Feat : 이미지 업로드 버튼 구현
  package-lock.json
  package.json
  src/components/UploadButtonImg/UploadButtonImg.jsx
  src/pages/SignUp/SignUpProfile.jsx
Labels: 📁 feat

#68 Feat : 게시물 상세페이지 구현
  src/App.jsx
  src/components/Header/LogoMoreHeader/LogoMoreHeader.jsx
  src/components/Layout/LogoMoreHeaderLayout/LogoMoreHeaderLayout.jsx
  src/components/Post/PostItem/PostItem.jsx
  src/components/Post/PostList/PostList.jsx
  src/pages/Community/CommunityDetail/CommunityDetail.jsx
  src/pages/Post/Post.jsx
Labels: 📁 feat

#72 Feat : 게시물 상세페이지 캐러셀 구현
  src/assets/images/icon-dot-current.svg
  src/assets/images/icon-dot.svg
  src/components/Carousel/Carousel.jsx
  src/components/CommuDetailContent/CommuDetailContent.jsx
  src/pages/Community/CommunityDetail/CommunityDetail.jsx
Labels: 📁 feat
