Repository R3act-lion/YOURTRIP, pull requests merged in 2023-01, with the labels that each got.

#74 Feat : 모달창 구현
  src/assets/images/icon-modal-bar.svg
  src/components/Comment/CommentItem/CommentItem.jsx
  src/components/Comment/PostComment/PostCommentListItem.jsx
  src/components/Header/BasicHeader/BasicHeader.jsx
  src/components/Header/LogoMoreHeader/LogoMoreHeader.jsx
  src/components/Layout/BasicHeaderLayout/BasicHeaderLayout.jsx
  src/components/Layout/ButtonHeaderLayout/ButtonHeaderLayout.jsx
  src/components/Layout/LogoHeaderLayout/LogoHeaderLayout.jsx
  src/components/Layout/LogoMoreHeaderLayout/LogoMoreHeaderLayout.jsx
  src/components/Modal/CommentModal.jsx
  src/components/Modal/DetailModal.jsx
  src/components/Modal/ModalBar.jsx
  src/components/Modal/ModalList.jsx
  src/components/Modal/MyPostModal.jsx
  src/components/Post/PostItem/PostItem.jsx
  src/components/Post/PostList/PostList.jsx
  src/pages/Community/Community.jsx
  src/pages/Community/CommunityDetail/CommunityDetail.jsx
  src/pages/Post/Post.jsx
Labels: 📁 feat

#75 bug : 프로필수정
  src/App.jsx
  src/components/Profile/UserInfo/UserInfo.jsx
  src/pages/Profile/ProfileModify/ProfileModify.jsx
Labels: 🚨 bug, 🧩 Refactor

#77 Feat : myProfile, yourProfile 구분 및 큐레이션 추가 기능
  src/App.jsx
  src/components/Navigation/Navigation.jsx
  src/components/Profile/UserInfo/UserInfo.jsx
  src/components/Profile/UserPlace/UserPlace.jsx
  src/components/SlideList/RecommendList/RecommendList.jsx
  src/components/SlideList/RecommendList/RecommendListItem.jsx
  src/components/SlideList/SelectedList/SelectedList.jsx
  src/components/SlideList/SelectedList/SelectedListItem.jsx
  src/pages/Profile/ProfileAddQuration/ProfileAddQuration.jsx
  src/pages/Profile/ProfileAddQuration/QurationPlaceList/QurationListItem.jsx
  src/pages/Profile/ProfileAddQuration/QurationPlaceList/QurationPlaceList.jsx
Labels: 📁 feat

#79 Feat : 팔로우, 언팔로우 기능 연결, 팔로우 카운트 연동
  src/App.jsx
  src/components/FollowingBtn/FollowingBtn.jsx
  src/components/Navigation/Navigation.jsx
  src/components/Profile/UserInfo/UserInfo.jsx
  src/components/Profile/UserPlace/UserPlace.jsx
  src/components/SlideList/RecommendList/RecommendList.jsx
  src/components/SlideList/RecommendList/RecommendListItem.jsx
  src/pages/Profile/Profile.jsx
Labels: 📁 feat

#80 Feat : 글쓰기 버튼 추가
  src/App.jsx
  src/assets/images/btn-write.svg
  src/components/Comment/CommentItem/CommentItem.jsx
  src/components/Comment/PlaceComment/PlaceCommentList.jsx
  src/components/Comment/PlaceComment/PlaceCommentListItem.jsx
  src/components/Comment/WriteComment/WriteComment.jsx
  src/components/CommuWritingButton/CommuWritingButton.jsx
  src/components/Header/BasicHeader/BasicHeader.jsx
  src/components/Modal/DetailModal.jsx
  src/components/Modal/DetailMyPostModal.jsx
  src/components/Modal/ModalList.jsx
  src/components/Modal/MyPostModal.jsx
  src/components/Post/PostItem/PostItem.jsx
  src/components/Post/PostList/PostList.jsx
  src/pages/Community/Community.jsx
  src/pages/Post/MyPost/MyDetailPost.jsx
  src/pages/Post/MyPost/MyPost.jsx
  src/pages/Post/Post.jsx
Labels: 📁 feat

#85 Feat : 검색 기능 구현
  src/App.jsx
  src/components/Header/SearchHeader/SearchHeader.jsx
  src/components/Layout/SearchHeaderLayout/SearchHeaderLayout.jsx
  src/components/Profile/UserPlace/UserPlace.jsx
  src/components/SearchResult/SearchResult.jsx
  src/components/SlideList/SelectedList/SelectedList.jsx
  src/components/UserDesc/UserDesc.jsx
  src/context/Context.jsx
  src/pages/Profile/ProfileAddQuration/QurationPlaceList/QurationPlaceList.jsx
Labels: 📁 feat

#87 Feat : 팔로워, 팔로잉 리스트 출력
  src/App.jsx
  src/components/FollowingBtn/FollowingBtn.jsx
  src/components/Profile/UserInfo/UserInfo.jsx
  src/components/Profile/UserPlace/UserPlace.jsx
  src/pages/Profile/ProfileFollowers/ProfileFollowers.jsx
  src/pages/Profile/ProfileFollowing/ProfileFollowing.jsx
Labels: 📁 feat

#91 Feat : 로그아웃 모달
  src/components/Header/BasicHeader/BasicHeader.jsx
  src/components/Layout/BasicHeaderLayout/BasicHeaderLayout.jsx
  src/components/Modal/DetailModal.jsx
  src/components/Modal/LogoutModal.jsx
  src/components/Modal/ProfileModal.jsx
Labels: 📁 feat

#90 Feat : 프로필수정기존정보불러오기
  src/components/Profile/UserInfo/UserInfo.jsx
  src/components/UploadButtonImg/UploadButtonImg.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/ProfileModify/ProfileModify.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpProfile.jsx
Labels: 📁 feat, 🧩 Refactor

#97 Fix : 프로필 오류 수정, 대체 이미지 적용
  src/components/Profile/UserInfo/UserInfo.jsx
  src/components/SlideList/SelectedList/SelectedList.jsx
  src/components/UploadButtonImg/UploadButtonImg.jsx
  src/components/UserDesc/UserDesc.jsx
  src/pages/Profile/ProfileFollowers/ProfileFollowers.jsx
  src/pages/Profile/ProfileFollowing/ProfileFollowing.jsx
  src/pages/Profile/ProfileModify/ProfileModify.jsx
Labels: 🔧 Fix

#94 Fix : 게시물 이미지 업로드 버튼 클릭시 버그 수정
  src/assets/images/btn-write.svg
  src/components/CommuWritingButton/CommuWritingButton.jsx
  src/pages/Community/CommunityUpload/CommunityUpload.jsx
Labels: 🚨 bug

#99 Fix : 페이지 링크 연결, 이미지 슬라이드 적용
  src/components/CommuWritingButton/CommuWritingButton.jsx
  src/components/ImageSlide/ImageSlide.jsx
  src/components/PlaceList/LocationList/LocationList.jsx
  src/components/Post/PostItem/PostItem.jsx
  src/components/SlideList/PostList/PostList.jsx
  src/components/SlideList/RecommendList/RecommendListItem.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceList.jsx
  src/components/SlideList/SimplePlaceList/SimplePlaceListItem.jsx
  src/pages/Community/CommunityUpload/CommunityUpload.jsx
  src/pages/Profile/ProfileAddQuration/ProfileAddQuration.jsx
  src/pages/Profile/ProfileAddQuration/QurationPlaceList/QurationListItem.jsx
  src/pages/Profile/ProfileAddQuration/QurationPlaceList/QurationPlaceList.jsx
Labels: 🔧 Fix

#101 Fix : 지역별 카테고리 내용 출력 수정
  src/components/PlaceList/LocationList/LocationList.jsx
  src/components/SlideList/DetailPlaceList/DetailPlaceList.jsx
  src/pages/Community/CommunityDetail/CommunityDetail.jsx
  src/pages/Location/LocationPlaceList/LocationPlaceList.jsx
Labels: 🔧 Fix

#105 Design : 하단 네비게이션 바 icon-fill 변경
  src/components/Navigation/Navigation.jsx
  src/components/SlideList/PostList/PostList.jsx
Labels: 🪡 Design

#107 Fix : 팔로워, 팔로잉 리스트 오류 수정
  src/components/FollowingBtn/FollowingBtn.jsx
  src/pages/Profile/ProfileFollowers/ProfileFollowers.jsx
  src/pages/Profile/ProfileFollowing/ProfileFollowing.jsx
Labels: 🔧 Fix

#110 Fix : 프로필 페이지 링크 수정
  src/pages/Login/Login.jsx
  src/pages/Profile/ProfileAddQuration/QurationPlaceList/QurationPlaceList.jsx
  src/pages/Profile/ProfileModify/ProfileModify.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUpProfile.jsx
Labels: 🔧 Fix

#114 Feat : 스플래쉬페이지구현
  src/App.jsx
  src/assets/images/YourTrip.svg
  src/assets/images/logo-bg.svg
  src/assets/images/logo-fg.svg
  src/pages/Profile/ProfileModify/ProfileModify.jsx
  src/pages/Splash/Splash.jsx
Labels: 📁 feat

#117 Feat : 댓글 삭제
  src/components/Comment/CommentItem/CommentItem.jsx
  src/components/Comment/PlaceComment/PlaceCommentListItem.jsx
  src/components/Modal/EditModal.jsx
  src/components/Modal/MyCommentModal.jsx
  src/pages/Community/CommunityDetail/CommunityDetail.jsx
Labels: 📁 feat
